### ISSUE TITLE
[Feature] Implement adapter tests in dbt-postgres

### ISSUE THREAD

**Issue by colin-rogers-dbt** [dbt-labs/dbt-postgres#4]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-postgres functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Currently dbt-postgres has implemented dbt-core's tests but doesn't reference the dbt-tests-adapter tests. 

```[tasklist]
### Tasks
- [ ] https://github.com/dbt-labs/dbt-adapters/pull/93
- [ ] https://github.com/dbt-labs/dbt-postgres/pull/18
```

**Comment by mikealfare** [comment]
Re-opening to resolve issues that were discovered in the original migration.
